# Rooshil Patel
# 1255318
# Assignment 2
# CMPUT 379

server_f: server_f.c
	gcc -Wall -o server_f server_f.c

server_p: server_p.c
	gcc -Wall -o server_p -pthread server_p.c 

clean:
	rm -f *.o server core
